global:
  resolve_timeout: 5m

route:
  receiver: discard
  group_by:
    - alertname
    - project
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - receiver: hexlet-5-email
      matchers:
        - project="hexlet-5"
        - severity=~"warning|critical"

receivers:
  - name: hexlet-5-email
    yandex_monitoring_configs:
      - send_resolved: true
        channel_names:
          - hexlet-5-email-alerts
  - name: discard
