apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hexlet-5-monitoring-credentials
  namespace: hexlet-5-monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hexlet-5-monitoring
    kind: SecretStore
  target:
    name: hexlet-5-monitoring-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: REPLACE_WITH_LOCKBOX_ID
        property: MONITORING_API_KEY
