apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: hexlet-5-application
  namespace: hexlet-5
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: hexlet-5-monitoring
  namespace: hexlet-5-monitoring
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key
