apiVersion: v1
kind: ConfigMap
metadata:
  name: hexlet-5-bulletin-board
  namespace: hexlet-5
data:
  SPRING_PROFILES_ACTIVE: prod
  MANAGEMENT_SERVER_PORT: "9090"
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: 30s
  STORAGE_S3_REGION: ru-central1
  STORAGE_S3_ENDPOINT: https://storage.yandexcloud.net
