apiVersion: v1
kind: Service
metadata:
  name: hexlet-5-bulletin-board
  namespace: hexlet-5
  labels:
    app.kubernetes.io/name: bulletin-board
    app.kubernetes.io/instance: hexlet-5
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: bulletin-board
    app.kubernetes.io/instance: hexlet-5
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30080
