apiVersion: v1
kind: Namespace
metadata:
  name: hexlet-5-gwin
---
apiVersion: v1
kind: Namespace
metadata:
  name: hexlet-5-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: hexlet-5-logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: hexlet-5-eso
